---

- name: Install differents web_servers
  hosts: all
  become: yes


  vars:
   source_file: /etc/ansible/index.html
   destination_file: /var/www/html

  tasks:
  - name: Check and Print Linux Version
    debug: var=ansible_os_family


  - block: #========== Block For Debian ==============
      - name: Install Apache For Debian
        apt: name=apache2 state=latest

      - name: Copy my web site
        copy: src={{ source_file }} dest={{ destination_file }} mode=0555
        notify: Restart Apache Debian

      - name: Start Web Server for Debian
        service: name=apache2 state=started enabled=yes

      - name: Check that you can connect (GET) to a page and it returns a status 200
        uri:
          url: http://10.0.2.9:80

      - name: Check that a page returns a status 200 and fail if the word Playbook is not in the page contents
        uri:
          url: http://10.0.2.9:80
          return_content: yes
        register: this
        failed_when: "'Playbook' not in this.content"

    when: ansible_os_family == "Debian"


  - block: #++++++++++ Block For RedHat +++++++++++

      - name: Install Nginx web Server for RedHat
        yum: name=nginx state=present

      - name: Copy my web site
        copy: src={{ source_file }} dest={{ destination_file }} mode=0555
        notify: Restart Nginx RedHat

      - name: Start Web Server for RedHat
        service: name=nginx state=started enabled=yes

      - name: Check that you can connect (GET) to a page and it returns a status 200
        uri:
         url: http://10.0.2.7:80

      - name: Check that a page returns a status 200 and fail if the word Playbook is not in the page contents
        uri:
           url: http://10.0.2.7:80
           return_content: yes
        register: this
        failed_when: "'Playbook' not in this.content"
    when: ansible_os_family == "RedHat"


  handlers:
      - name: Restart Apache Debian
        service: name=nginx state=restarted

      - name: Restart Nginx RedHat
        service: name=httpd state=restarted
